#!/usr/bin/env bash
# This script story tells.

while IFS= ":" read -r username password UID GID GECOS home shell ; do
 echo "The user $username is part of the $GID gang, lives in $home and rides $shell. $UID place is protected by the passcode $password, more info about the user here: GECOS"

done < /etc/passwd
