#!/usr/bin/env bash
# This script uses case to show displays after specific lines.
 
m=1
while [ "$m" -le 20 ] ; do
	echo "$m"
	case "$m" in
	   4) 
	      echo "bad luck from China"
	      ;;
 	   9) 
 	      echo "bad luck from Japan"
	      ;;
	   17)
	      echo "bad luck from Italy"
	      ;;
	esac
	m=$((m+1))
done
