#!/usr/bin/env bash
# This scripy creates a file,diplays texts indefinetly and after recieving signals and as well deletes a file.

echo "$$" >> /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm-f  /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

while true
do
	echo "To infinity and beyond"
done
