#!/usr/bin/env bash
# This script manages manage_my_process

fpid="/var/run/my_process.pid"
case "$1" in
	start)
	     ./manage_my_process &
	     echo $! > "$fpid"
	     echo "manage_my_process started"
	     ;;
	stop)
  	     if [ -f "$fpid" ]; then
	         pkill -f manage_my_process
	         rm -f "$fpid"
	         echo "manage_my_process stopped"
	     fi
             ;;
 	restart)
	  if [ -f "$fpid" ]; then
	     pkill -f manage_my_process
	     rm -f "$fpid"
	  fi
	     ./manage_my_process &
	     echo $! > "$fpid"
	     echo "manage_my_process has restarted"
	     ;;
 	*)
	  echo "Usage: manage_my_process {start|stop|restart}"
	  exit 1
	  ;;
esac 
