#!/usr/bin/env bash
# This script manages manage_my_process

start() {
    manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop() {
    kill $(cat /var/run/my_process.pid) 2>/dev/null
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
