#!/usr/bin/env bash
# This script displays I am invincible!!! when it recieves a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
   echo "To infinity and beyond"
   sleep 2
   
done
